name: scopa_app
description: An app to play Scopa.
publish_to: 'none'

version: 0.4.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  scopa_lib:
    git:
      url: https://github.com/mnowakowski98/scopa_lib 
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  mockito: ^5.4.3

flutter:
  uses-material-design: true
